Save and load studyPlans + loades courses from json
Tetre2/Project-Ocean pull request #20
Opened 2019-10-08 14:47 UTC by Tetre2

2019-10-09 09:37 UTC, Eyzic requested changes
Does not run. FileNotFound. I think you need to create directories.

2019-10-09 15:02 UTC, Eyzic requested changes
Overall good, but a couple of changes is needed. Primarily to break down big methods into smaller ones and giving them good names.

2019-10-09 15:02 UTC, Eyzic commented on src/main/java/ProjectOcean/IO/CoursesSaverLoader.java
> +import java.util.*;
Check if you really need to import all of util or if you only need some lists.

2019-10-09 15:02 UTC, Eyzic commented on src/main/java/ProjectOcean/IO/CoursesSaverLoader.java
> +        File file = new File(getHomeDirPath() + fileName);
file verkar inte användas någon gång.

2019-10-09 15:02 UTC, Eyzic commented on src/main/java/ProjectOcean/IO/CoursesSaverLoader.java
> +    }
The comments are good, but it would be easier to read if you could use the comments as a basis for making smaller methods and calling them instead. There is to much going on in the same method. TL;DR abstract into smaller methods.

2019-10-09 15:02 UTC, Eyzic commented on src/main/java/ProjectOcean/IO/CoursesSaverLoader.java
> +        return loadCourses();
Do the call to loadCourses twice at a higher level instead to avoid an infinite error loop. Seems like that responsibility belongs to the higher class.

2019-10-09 15:02 UTC, Eyzic commented on src/main/java/ProjectOcean/Controller/ApplicationController.java
> +
This method is empty? Any specific reason why?

2019-10-09 15:02 UTC, Eyzic commented on src/main/java/ProjectOcean/Controller/WorkspaceController.java
> +        displayAllCoursesInWorkspace();
Should be removed. Instead end your call in CoursePlanningSystem with setChanged() and notifyObservers()

2019-10-09 15:02 UTC, Eyzic commented on src/main/java/ProjectOcean/Model/Schedule.java
> +    public void tryAddCourse(Course course, int year, int studyPeriod, int slot) {
Rename to addCourse. Its up to higher level caller to handle exceptions.

2019-10-09 15:02 UTC, Eyzic commented on src/main/java/ProjectOcean/Model/Student.java
> +    }
Maybe think about whether we can create a student without any parameters and in the constructor load instead. Not entirely sure, but we could have a discussion.

2019-10-09 15:02 UTC, Eyzic commented on src/main/java/ProjectOcean/Model/StudyPeriod.java
> +
Break out into a smaller method that explains what it actually does more clearly.

2019-10-09 15:02 UTC, Eyzic commented on src/main/java/ProjectOcean/IO/StudyPlanSaverLoader.java
> +    }
Break into smaller methods and explain what they are doing.

2019-10-09 15:02 UTC, Eyzic commented on src/main/java/ProjectOcean/IO/StudyPlanSaverLoader.java
> +        return loadStudent();
Try to lett the caller take care of calling twice if needed.

2019-10-09 15:02 UTC, Eyzic commented on src/main/java/ProjectOcean/IO/StudyPlanSaverLoader.java
> +    }
Break into smaller methods and explain what they do.

2019-10-10 11:12 UTC, Tetre2 commented on src/main/java/ProjectOcean/Controller/WorkspaceController.java
> +        displayAllCoursesInWorkspace();
Does not work and other suggested methods of solving it wouldn't work either

2019-10-11 08:17 UTC, Eyzic requested changes
A few changes needed, other wise good.

2019-10-11 08:17 UTC, Eyzic commented on src/main/java/ProjectOcean/Controller/ApplicationController.java
> +import ProjectOcean.IO.StudyPlanSaverLoader;
Unused imports.

2019-10-11 08:17 UTC, Eyzic commented on src/main/java/ProjectOcean/Controller/ApplicationController.java
> +    @FXML
Move FXML tag under javadoc

2019-10-11 08:17 UTC, Eyzic commented on src/main/java/ProjectOcean/Controller/YearController.java
> +
Who is George? And why is he here?

2019-10-11 08:17 UTC, Eyzic commented on src/main/java/ProjectOcean/Controller/YearController.java
> +    private void George(){
You are responsible for the code your write. Will not let George through the review.

2019-10-11 08:17 UTC, Eyzic commented on src/main/java/ProjectOcean/IO/CoursesSaverLoader.java
> +    public Map<UUID, Course> tryToLoadCoursesFileIfNotCreateNewFile(){
Seems like the method is doing two things. Maybe break it out in two methods and do the if statement at a higher level.

2019-10-11 08:17 UTC, Eyzic commented on src/main/java/ProjectOcean/IO/ICourseSaveLoader.java
> +    Map<UUID, Course> tryToLoadCoursesFileIfNotCreateNewFile();
See other comment about splitting the method.

2019-10-11 08:17 UTC, Eyzic commented on src/main/java/ProjectOcean/IO/IStudyPlanSaverLoader.java
> +    Student tryToLoadStudentFileIfNotCreateNewFile();
Same as the other comments about this method

2019-10-11 08:17 UTC, Eyzic commented on src/main/java/ProjectOcean/IO/StudyPlanSaverLoader.java
> +    public Student tryToLoadStudentFileIfNotCreateNewFile(){
Maybe break out into two methods.

2019-10-11 08:17 UTC, Eyzic commented on src/main/java/ProjectOcean/Model/CoursePlanningSystem.java
> +            return model = new CoursePlanningSystem(studyPlanSaverLoader.tryToLoadStudentFileIfNotCreateNewFile(), courseSaveLoader.tryToLoadCoursesFileIfNotCreateNewFile());
Try to make the line visible without horizontal scrolling

2019-10-11 08:17 UTC, Eyzic commented on src/main/java/ProjectOcean/Model/Schedule.java
> +        //TODO möjligt ställe koden dör
Remove comments if its fixed

2019-10-11 08:17 UTC, Eyzic commented on src/main/java/ProjectOcean/Model/Student.java
> -        studyPlans.add(this.currentStudyPlan);
Why is this removed? Seems like we would want that line of code.

2019-10-11 08:17 UTC, Eyzic commented on src/main/java/ProjectOcean/Model/Student.java
> +     * @param currentStudyPlan the
Do we need this functionality?

2019-10-11 08:17 UTC, Eyzic commented on src/test/java/ProjectOcean/IO/StudyPlanSaverLoaderTests.java
> +        //---- studyPlan 1 ----
StudyPlan 2?

2019-10-11 11:35 UTC, Eyzic approved these changes

2019-10-11 11:36 UTC, merged