Develop
Tetre2/Project-Ocean pull request #26
Opened 2019-10-15 14:57 UTC by Tetre2

2019-10-15 15:20 UTC, Eyzic requested changes
Looks good overall. Look through the test files and format so that empty lines are gone and make sure it follows our code standards.  Some changes needed on some unprofessional strings.

2019-10-15 15:20 UTC, Eyzic commented on src/main/java/ProjectOcean/IO/StudyPlanSaverLoader.java
> +    public void createNewStudentFile(){
Missing javadoc

2019-10-15 15:20 UTC, Eyzic commented on src/main/java/ProjectOcean/Main.java
> +    @Override
Feels stupid, but javadoc

2019-10-15 15:20 UTC, Eyzic commented on src/main/java/ProjectOcean/Model/Course.java
> +    public boolean equals(Object o) {
Do you need javadoc on overidden methods? If yes then missing javadoc

2019-10-15 15:20 UTC, Eyzic commented on src/main/java/ProjectOcean/Model/Course.java
> +    @Override
Do you need javadoc on overidden methods? If yes then missing javadoc

2019-10-15 15:20 UTC, Eyzic commented on src/test/java/ProjectOcean/Model/CourseTests.java
> +    //These tests come from CPS test, but where removed because the methods where removed from CPS.
A lot of outcommented code. Fix before merge with master.

2019-10-15 15:20 UTC, Eyzic commented on src/test/java/ProjectOcean/Model/ScheduleTests.java
> +
Make the format more clean. Kill empty lines.

2019-10-15 15:20 UTC, Eyzic commented on src/test/java/ProjectOcean/Model/StudentTests.java
> +
Delete a line

2019-10-15 15:20 UTC, Eyzic commented on src/test/java/ProjectOcean/Model/StudyPeriodTests.java
> +
Delete one line

2019-10-15 15:20 UTC, Eyzic commented on src/test/java/ProjectOcean/Model/StudyPlanTests.java
> +
Delete empty lines

2019-10-15 15:20 UTC, Eyzic commented on src/test/java/ProjectOcean/WorkspaceTest.java
> +    public void createCourses() {
Change from LINK and Abu Dhabi to something more professional. Applies to all the tests below.

2019-10-15 18:19 UTC, Tetre2 commented on src/test/java/ProjectOcean/Model/ScheduleTests.java
> +
Dom är dödade!

2019-10-16 09:28 UTC, Eyzic approved these changes

2019-10-16 11:09 UTC, merged